# Generated by Django 5.0.4 on 2024-10-18 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange_binance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='copytradeaccount',
            name='available_balance',
            field=models.FloatField(default=0.0, verbose_name='Available balance'),
        ),
        migrations.AddField(
            model_name='copytradeaccount',
            name='cross_unrealized_pnl',
            field=models.FloatField(default=0.0, verbose_name='Cross unrealized PNL'),
        ),
        migrations.AddField(
            model_name='copytradeaccount',
            name='margin_balance',
            field=models.FloatField(default=0.0, verbose_name='Margin balance'),
        ),
        migrations.AddField(
            model_name='copytradeaccount',
            name='unrealized_pnl',
            field=models.FloatField(default=0.0, verbose_name='Unrealized PNL'),
        ),
        migrations.AddField(
            model_name='masteraccount',
            name='available_balance',
            field=models.FloatField(default=0.0, verbose_name='Available balance'),
        ),
        migrations.AddField(
            model_name='masteraccount',
            name='cross_unrealized_pnl',
            field=models.FloatField(default=0.0, verbose_name='Cross unrealized PNL'),
        ),
        migrations.AddField(
            model_name='masteraccount',
            name='margin_balance',
            field=models.FloatField(default=0.0, verbose_name='Margin balance'),
        ),
        migrations.AddField(
            model_name='masteraccount',
            name='unrealized_pnl',
            field=models.FloatField(default=0.0, verbose_name='Unrealized PNL'),
        ),
        migrations.AlterField(
            model_name='mainsettings',
            name='signal_source_name',
            field=models.CharField(choices=[('RSI', 'RSI'), ('TLG', 'TLG')], default='RSI', verbose_name='Signal source'),
        ),
        migrations.AlterField(
            model_name='position',
            name='notional',
            field=models.FloatField(help_text='notional', null=True, verbose_name='Notional USDT'),
        ),
    ]
