# Generated by Django 5.0.4 on 2024-10-18 04:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exchange_binance', '0002_copytradeaccount_available_balance_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='copytradeaccount',
            old_name='unrealized_pnl',
            new_name='unrealized_profit',
        ),
        migrations.RenameField(
            model_name='masteraccount',
            old_name='unrealized_pnl',
            new_name='unrealized_profit',
        ),
    ]
