# Generated by Django 5.0.4 on 2024-10-24 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange_binance', '0003_rename_unrealized_pnl_copytradeaccount_unrealized_profit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='liquidation_price',
            field=models.FloatField(help_text='liquidationPrice', null=True, verbose_name='Liquidation price'),
        ),
    ]
