# Generated by Django 5.0.4 on 2024-11-07 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange_binance', '0004_position_liquidation_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='copytradeorder',
            name='transaction_time',
            field=models.BigIntegerField(help_text='transaction time', null=True, verbose_name='Transaction time'),
        ),
        migrations.AddField(
            model_name='order',
            name='transaction_time',
            field=models.BigIntegerField(help_text='transaction time', null=True, verbose_name='Transaction time'),
        ),
        migrations.AddField(
            model_name='position',
            name='transaction_time',
            field=models.BigIntegerField(help_text='transaction time', null=True, verbose_name='Transaction time'),
        ),
        migrations.AlterField(
            model_name='masteraccount',
            name='api_key',
            field=models.CharField(blank=True, max_length=100, verbose_name='API key'),
        ),
        migrations.AlterField(
            model_name='masteraccount',
            name='api_secret',
            field=models.CharField(blank=True, max_length=100, verbose_name='API secret'),
        ),
    ]
