# Generated by Django 5.0.4 on 2024-11-26 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange_binance', '0005_copytradeorder_transaction_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainsettings',
            name='coefficient',
            field=models.FloatField(default=1.0, verbose_name='Coefficient'),
        ),
    ]
